name: Deploy to production

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Edit .env for production
        run: sed -i '/APP_ENV=dev/c\APP_ENV=prod' .env

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Optimize dependencies
        run: composer dump-autoload --optimize --classmap-authoritative

      - name: Install Node & dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Build assets
        run: npm run build

      - name: Clean unused files and directories
        run: rm -rf .git .github .idea .env .gitignore composer.lock symfony.lock var/cache/prod database.png

      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "*"
          target: "sites/mcu-api.thoanny.fr"

      - name: multiple command
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd sites/mcu-api.thoanny.fr
            php bin/console doctrine:migrations:migrate
            php bin/console cache:clear